CREATE ROLE "movie-user" NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS PASSWORD '<PUT_PASSWORD_USER>';
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE public.movies TO "movie-user";
