# On /.github/workflows hola-mundo.yml
name: hola-mundo
on: 
  push:
    branches: ["develop"]
jobs: 
  hola-mundo:
    runs-on: ubuntu-latest
    steps: 
      -name: Hola Mundo
       run: python hola_mundo.py
