name: hola-mundo
on: [push]
jobs: 
  hola-mundo:
    runs-on: ubuntu-latest
    steps: 
      -name: Public IP
       uses: haythem/public-ip@v1.3
       id: ip       
      -name: Hola Mundo 
       run: echo !Hola Mundo desde ${{steps.ip.outputs.ipv4 }}! 
